apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-hello-world-nginx-content
data:
  index.html: |
    {{ .Files.Get "files/index.html" | nindent 4 }}
  style.css: |
    {{ .Files.Get "files/style.css" | nindent 4 }}
