apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hello-world-spring-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-world-spring
  template:
    metadata:
      labels:
        app: hello-world-spring
    spec:
      containers:
        - name: hello-world-spring
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80