apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-hello-world-spring-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /hello-world-spring
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-hello-world-spring-service
                port:
                  number: 80
