apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dafywinf/argocd-deployment
    targetRevision: HEAD
    path: argo-apps/user-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true